---
sudo: required
dist: xenial
cache: bundler
language: python
python: "2.7"
#virtualenv:
#  system_site_packages: true
services:
  - postgresql
addons:
  postgresql: "9.5"
  apt:
    packages:
      - postgresql-9.5
      - postgresql-client-9.5
      - postgresql-server-dev-9.5

env:
  - task: LINT
  - task: BUILD

before_install:
  - |
    if [ "${task}" == "BUILD" ]; then
      # Remove extra postgres versions from travis
      sudo systemctl postgresql stop
      sudo apt remove --purge postgresql-9.4* postgresql-9.6* postgresql-10*
      sudo rm -f /etc/apt/sources.list.d/pgdg.list
      # Remove RVM from travis
      rvm implode --force
      sudo rm -rf $HOME/.rvm $HOME/.rvmrc /etc/rvmrc /etc/profile.d/rvm.sh /usr/local/rvm /usr/local/bin/rvm
      sed '/rvm/d' /home/travis/.bashrc
      sed '/rvm/d' /home/travis/.bash_profile
      sed '/rvm/d' /home/travis/.profile
      gem uninstall rvm
      unset GEM_HOME
      unset GEM_PATH
      unset RUBY_VERSION
      unset MY_RUBY_HOME
      unset IRBRC
    fi

install:
  - sudo add-apt-repository -y ppa:ansible/ansible-2.9
  - sudo apt update -q
  - sudo apt install -y ansible python-apt
  - pip install 'ansible-lint==4.1.0'

script:
  - bin/setup
  - |
    if [ "${task}" == "LINT" ]; then
      ansible-lint playbooks/*.yml --exclude community
    fi
  - |
    if [ "${task}" == "BUILD" ]; then
      ansible-playbook tests/suite.yml --limit travis --connection local -vv
    fi
