---

- name: extract host_id from filepath
  set_fact:
    secrets_host_id: "{{ secrets_host_path.path.split('/tmp/ofn-secrets/')[1] }}"

- name: copy {{ secrets_host_id }} secrets file to relevant host_vars directory
  copy:
    src: "{{ secrets_host_path.path }}/secrets.yml"
    dest: "../inventory/host_vars/{{ groups[secrets_host_id][0] }}/secrets.yml"
    decrypt: no
  when: secrets_host_id != 'db-servers'

- name: copy dbserver keys
  copy:
    src: "{{ secrets_host_path.path }}/keys/{{ dbserver_key }}"
    dest: "../files/dbserver_keys/{{ dbserver_key }}"
    decrypt: no
  loop:
    - "{{ unicorn_user }}.crt"
    - "{{ unicorn_user }}.key"
    - postgres.crt
    - postgres.key
    - server.crt
    - server.key
    - root.crt
  loop_control:
    loop_var: dbserver_key
  when: secrets_host_id == 'db-servers'
