--- # Compatibility

- name: install packages for Ubuntu 16
  apt:
    name: "{{ xenial_packages }}"
  become: yes
  vars:
    xenial_packages:
      - python-software-properties
  when: ansible_distribution_major_version == '16'

- name: add libssl1.0-dev source for Ubuntu 18+
  apt_repository:
    repo: deb http://security.ubuntu.com/ubuntu bionic-security main
    update_cache: yes
  become: yes

- name: install packages for Ubuntu 18+
  apt:
    name: "{{ bionic_packages }}"
  become: yes
  vars:
    bionic_packages:
      - software-properties-common
  when: ansible_distribution_major_version >= '18'

- name: define additional rbenv build dependencies for Ruby on Ubuntu 18+
  set_fact:
    rbenv_extra_depends:
      - libssl1.0-dev
  when: ansible_distribution_major_version >= '18'
