---

- name: dump the database
  postgresql_db:
    name: "{{ db }}"
    login_host: "{{ postgres_module_login_host }}"
    state: dump
    target: "{{ remote_backup_path }}"
  environment: "{{ postgres_module_ssl_env }}"
  become: yes
  become_user: postgres

- name: fetch database dump
  fetch:
    src: "{{ remote_backup_path }}"
    dest: "{{ local_backup_path }}"
    fail_on_missing: yes
    flat: yes

- name: delete the db dump on the server
  file:
    dest: "{{ remote_backup_path }}"
    state: absent
  become: yes
