---

- name: ensure keys path exists
  file:
    path: "/home/{{ dbserver_user }}/.postgresql"
    state: directory
    owner: postgres
    mode: 0600

- name: provision dbserver keys
  copy:
    src: "{{ lookup('file', inventory_dir + '/../files/dbserver_keys/' + dbserver_key ) }}"
    dest: "/home/{{ dbserver_user }}/.postgresql/{{ dbserver_key }}"
    owner: postgres
    mode: 0600
  loop: "{{ dbserver_certs }}"
  loop_control:
    loop_var: dbserver_key
