---

- name: install postgres
  import_role:
    name: geerlingguy.postgresql
  become: yes
  become_user: root
  vars:
    postgresql_databases:
      - name: "{{ db }}"
        owner: "{{ db_user }}"
        login_password: "{{ db_password }}"
        lc_collate: "{{ postgres_encoding }}"
        lc_ctype: "{{ postgres_encoding }}"
    postgresql_users:
      - name: "{{ db_user }}"
        password: "{{ db_password }}"
        role_attr_flags: "{{ db_user_roles }}"
