---

- name: add postgresql signing key
  apt_key:
    url: "https://www.postgresql.org/media/keys/ACCC4CF8.asc"
  become: yes

- name: add offical postgresql repo
  apt_repository:
    repo: "deb http://apt.postgresql.org/pub/repos/apt/ {{ ansible_distribution_release }}-pgdg main"
    filename: pgdg
  become: yes

- name: install postgres {{ pg_new }}
  apt:
    name: "postgresql-{{ pg_new }}"
  become: yes
